server:
  port: 8072

spring:
  application:
    name: eureka-client
    
  profiles:
    active: insecure
    
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    kr.or.wanna: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
    appname: eureka-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        
     