spring:
  application:
    name: hello-server1
    
server:
  port: 8701
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
