spring:
  application:
    name: hello-server2
    
server:
  port: 8702
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
